variables:
- template: /.azuredevops/pipeline_templates/config.yml
# Create booleans for branches we want to build.
# TODO: place in config?
- name: isMain
  value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
- name: isDev
  value: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
- name: PublishPackage
  value: False


stages:
  - stage: PreCommit
    jobs:
      - job: ExecutePreCommit
        displayName: "Perform pre-commit checks"
        steps:
        - template: /.azuredevops/pipeline_templates/pre-commit.yml
          parameters:
            pythonVersion: '$(pythonVersion)'

{% if cookiecutter.poetry_package_mode -%}
  - stage: Build
    jobs:
      - job: Build
        displayName: "Build and store staging artifact"
        steps:
          - template: /.azuredevops/pipeline_templates/build.yml
            parameters:
              pythonVersion: '$(pythonVersion)'
{%- else -%}
# No build step added, since poetry_package_mode is set to false during cookiecutter initialization.
# To change this, set the package-mode value in the pyproject.toml to true, and add a build step here.
{% endif %}