name: {{cookiecutter.project_slug}}
channels:
  - conda-forge
  - defaults
  - nodefaults
dependencies:
  - python=={{cookiecutter.python_version}}
  - chardet=5.2.0
  - conda-lock=1.4.0
  - ipykernel=6.21.1
  - pip==23.0
  - numpy
  - pandas
  - scikit-learn