steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'
  - script: |
      python -m pip install --upgrade pip
      python -m pip install -r tests/test_requirements.txt
    displayName: 'Install dependencies'
